### ISSUE TITLE
能先支持下拖拽上传吗？

### ISSUE THREAD

**Issue by lingchuanbo** [PingKuNet/aliyunpan#1]
您好 能否先优先支持下拖拽上传 这样就可以放弃V2版本了

**Comment by lingchuanbo** [comment]
还有一个下载功能

**Comment by PingKuNet** [comment]
> 同求 我这边拖拽上传 或者单文件选择上传 都是无效的 有提示 但是实际没有上传任务

你用的是我这个版本吗？
https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha

在我自己的机子上，测试上传是OK的，不会自动跳转到上传中哦，现在在主页面也不会显示，要自己切换到“传输”->“上传中”查看，现在“已上传完”还没有做好，小文件可能很快就上传完成了，要在网盘文件中查看了。

**Comment by PingKuNet** [comment]
> 您好 能否先优先支持下拖拽上传 这样就可以放弃V2版本了

我都忘记了这事，感谢提醒，由于原作者已经实现了拖拽事件，我在里面完成上传动作就可以了，所以已经完成了。
一会就上传代码，将会在下载功能实现后发布一个测试版本，应该会在这个月完成基本能用的下载。

**Comment by PingKuNet** [comment]
> > > 同求我拖拖拉拉或者单文件选择上传都是错误的，其实是上传的，
> > 
> > 
> > 你用的是我这个版本吗？ https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面也不会，要自己切换到“传输”->“上传中”查看，现在“上传完成” ”很快还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> 
> 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有文件 是不是不支持 文件夹上传？

是的不支持“文件夹上传”（现在是在网盘创建了个空文件夹，没什么用哈哈）菜单没有关，让你误会了，只支持上传文件，但可以多选。

**Comment by PingKuNet** [comment]
> > > 同求我拖拖拉拉或者单文件选择上传都是错误的，其实是上传的，
> > 
> > 
> > 你用的是我这个版本吗？ https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面也不会，要自己切换到“传输”->“上传中”查看，现在“上传完成” ”很快还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> 
> 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有文件 是不是不支持 文件夹上传？

选择上传的时候提示什么错误了，可以发出来看下吗？或者到设定-》远行日志-》复制日志-》贴出来看下。

**Comment by PingKuNet** [comment]
> > > 同求我拖拖拉拉或者单文件选择上传都是错误的，其实是上传的，
> > 
> > 
> > 你用的是我这个版本吗？ https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面也不会，要自己切换到“传输”->“上传中”查看，现在“上传完成” ”很快还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> 
> 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有文件 是不是不支持 文件夹上传？

选择上传的时候提示什么错误了，可以发出来看下吗？或者到设定-》远行日志-》复制日志-》贴出来看下。

**Comment by PingKuNet** [comment]
> > > 同求我拖拖拉拉或者单文件选择上传都是错误的，其实是上传的，
> > 
> > 
> > 你用的是我这个版本吗？ https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面也不会，要自己切换到“传输”->“上传中”查看，现在“上传完成” ”很快还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> 
> 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有文件 是不是不支持 文件夹上传？

选择上传的时候提示什么错误了，可以发出来看下吗？或者到设定-》远行日志-》复制日志-》贴出来看下。

**Comment by PingKuNet** [comment]
> > > > > 同求我拖拉拉拉或者单文件选择上传都是错误的，其实是上传的，
> > > > 
> > > > 
> > > > 你用的是我这个版本吗？https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > > > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面不会，要自己切换到“传输”->“上传中”查看，现在“上传完成””还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> > > 
> > > 
> > > 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有是不是不支持文件夹上传？
> > 
> > 
> > 是的不支持“文件夹上传”（现在是在网盘创建了个空文件夹，没什么用哈哈菜单）没有，让你误会了，只支持上传文件，但可以多选。
> 
> 原来是这样，那希望优化下，因为文件夹下面有些还有子文件夹，希望可以直接拖拽文件夹，遍历下面的子文件夹都上传

这个后面会做的，现在先把下载先实现了

**Comment by PingKuNet** [comment]
> > > > > 同求我拖拉拉拉或者单文件选择上传都是错误的，其实是上传的，
> > > > 
> > > > 
> > > > 你用的是我这个版本吗？https://github.com/PingKuNet/aliyunpan/releases/tag/v3.8.25.alpha
> > > > 我自己的机子上，测试上传OK的，不会自动跳转到上传中哦，现在在主页面不会，要自己切换到“传输”->“上传中”查看，现在“上传完成””还没有，小文件可能就上传完成了，要在网盘文件中查看了。
> > > 
> > > 
> > > 是的就是这个版本，提示创建上传任务了，点到上传中都没有任务，网盘里也没有是不是不支持文件夹上传？
> > 
> > 
> > 选择上传的时候提示什么错误，可以发出下贴吗？或者到设定-》远行日志-》复制日志-》出来看下。
> 
> 额 这个不是错误吧 你不是说现在不支持文件夹上传 只支持单文件上传吗 日志只有这些
> 
> 25 20:34:51 : success : 小白羊启动 25 20:11:33 : success : 小白羊启动 25 19:03:15 : success : 小白羊启动 25 19:03:03 : success : 小白羊启动

好吧

**Comment by PingKuNet** [comment]
> 您好 能否先优先支持下拖拽上传 这样就可以放弃V2版本了

版本已发布 #12

**Comment by PingKuNet** [comment]
> 还有一个下载功能

新版已有下载，但还不是很完善 #12

**Comment by snow212-cn** [comment]
能不能支持下拖拽移动文件  从一个目录到另一目录
