### ISSUE TITLE
上传大文件时发生错误

### ISSUE THREAD

**Issue by misaka7711** [PingKuNet/aliyunpan#17]
反馈一下，当上传大量文件时，一段时间后进度会卡住，直到客户端退出重启方可恢复。v3.09.13
```
HttpError4 status=401 code=AccessTokenInvalid message=Request failed with status code 401
HttpError4 status=401 code=AccessTokenInvalid message=Request failed with status code 401
HttpError4 status=401 code=AccessTokenInvalid message=Request failed with status code 401
HttpError4 status=404 code=NotFound.UploadId message=Request failed with status code 404
HttpError4 status=404 code=NotFound.UploadId message=Request failed with status code 404
HttpError4 status=404 code=NotFound.UploadId message=Request failed with status code 404
```

> 已上传上传约1TB文件，账号已开通 svip

**Comment by PingKuNet** [comment]
你好，HTTP401错误代表用户没有访问权限，需要进行身份认证。

如果当时你能打开文件，能打开文件夹，或者能做其它操作，就是不能上传，那么大概率是被官方临时限制了。

从HTTP的状态码分析，status=404 code=NotFound.UploadId，代表是这个API请求的资源没有找到（有访问权限）
有部分的API能访问，有部分API不能访问，这样分析就是被限制了

**Comment by PingKuNet** [comment]
> 已上传上传约1TB文件，账号已开通 svip

不知道你这种需求，设置少一点同时上传，还会不会被限制

**Comment by misaka7711** [comment]
感谢回复，目前更换回官方客户端后暂时恢复了正常的上传。
前面我也有猜到 上传太多文件会被官方限制，只是没想到在开通 svip 的情况下，使用第三方工具上传`1TB`左右就频繁出现 401、404这样的错误。
