### ISSUE TITLE
amd CPU还是会蓝屏

### ISSUE THREAD

**Issue by tangqiu0205** [PingKuNet/aliyunpan#29]
几乎是必现的, 只要是退出软件, 系统必蓝屏.

**Comment by PingKuNet** [comment]
> 几乎是必现的, 只要是退出软件, 系统必蓝屏.

你好，可以说一下你的电脑的配置信息吗？包括系统版本，我在小米的笔记本amd CPU上测试了  32位和64位，都没有问题。

看下运行日志有没有报错，有的话可以贴出来一下。

**Comment by tangqiu0205** [comment]
设备名称	LAPTOP-1L0799RG
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
GPU                  GTX1650

版本	Windows 11 家庭中文版
版本	22H2
操作系统版本	22621.608

<img width="621" alt="image" src="https://user-images.githubusercontent.com/37826977/194742461-8693c964-9f3f-4b26-8e50-a06c40aaa440.png">

**Comment by PingKuNet** [comment]
这个暂时也没有看出什么问题来，不过个个版本上传下载时间长了，数量多了，本身是有问题的没有优化好。

#21
