### ISSUE TITLE
自行打包mac版本：启动出现多个f12弹窗，如何修改配置让他不启动这么多弹窗呢？

### ISSUE THREAD

**Issue by gclm** [PingKuNet/aliyunpan#37]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/27618687/198917617-c78a8b47-f618-47f1-adad-ceae64ff45da.png">

**Comment by PingKuNet** [comment]
你这个应该是使用了“dev”模式，
使用“build”指令后，再运行输出物

输出物在  ->  release -> *

最新的代码  下载功能没有做好

你也可以使用 tag -> v3.9.13-beta 的代码打包

**Comment by gclm** [comment]
感谢，目前已经可以正常打包了
