### ISSUE TITLE
你好 请问为什么3.8.25为什么显示找不到文件啊 看不了视频

### ISSUE THREAD

**Issue by 857857-lps** [PingKuNet/aliyunpan#5]
所有视频都打不开

**Comment by PingKuNet** [comment]
> 所有视频都打不开

你好，是这是因为，我在打包的时候没有添加播放插件引起的。

解决方法：
方法一：自定义播放软件
如下图就是设置成旧版中的MPV播放器
![image](https://user-images.githubusercontent.com/48786066/187184704-ef580cbe-2020-4bc1-b3b4-dd533c3db0c9.png)

方法二：使用内置网页播放器
如上设置页面中先后“内置网页播放器”

方法三：不修改设置，下载MPV播放器
将下载的MPV播放器，解压到应用程序的resources目录就即可
详细路径可以参考上图旧版的路径

MPV播放器下载地址
https://wwb.lanzouv.com/b03p8ocib
密码:74e4

**Comment by jay799089587** [comment]
违规视频可以看吗

**Comment by PingKuNet** [comment]
> 添加播放插件

新版本已发布，已添加播放插件打包 #12
